version: '3.8'

services:
  # --- MySQL ---
  mysqldb:
    image: mysql:9
    container_name: squid-game-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: SquidGameMS
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Backend ---
  backend:
    build: .
    container_name: squidgame-backend
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/SquidGameMS
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always

  # --- Frontend ---
  frontend:
    build:
      # ВАРІАНТ 1: Відносний шлях (якщо папки поруч)
      context: ../squid-game-vite-ui

      # ВАРІАНТ 2: Повний шлях (найнадійніший, якщо папки далеко)
      # Заміни на свій реальний шлях до папки з React!
      # context: /Users/sasha/Documents/Work/squid-game-frontend

      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8080/api"
    container_name: squidgame-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    name: squid-network